const countries = [
  { code: "+93", label: "Afghanistan", iso: "af" },
  { code: "+355", label: "Albania", iso: "al" },
  { code: "+213", label: "Algeria", iso: "dz" },
  { code: "+376", label: "Andorra", iso: "ad" },
  { code: "+244", label: "Angola", iso: "ao" },
  { code: "+1", label: "Antigua and Barbuda", iso: "ag" },
  { code: "+54", label: "Argentina", iso: "ar" },
  { code: "+374", label: "Armenia", iso: "am" },
  { code: "+297", label: "Aruba", iso: "aw" },
  { code: "+61", label: "Australia", iso: "au" },
  { code: "+43", label: "Austria", iso: "at" },
  { code: "+994", label: "Azerbaijan", iso: "az" },
  { code: "+1", label: "Bahamas", iso: "bs" },
  { code: "+973", label: "Bahrain", iso: "bh" },
  { code: "+880", label: "Bangladesh", iso: "bd" },
  { code: "+1", label: "Barbados", iso: "bb" },
  { code: "+375", label: "Belarus", iso: "by" },
  { code: "+32", label: "Belgium", iso: "be" },
  { code: "+501", label: "Belize", iso: "bz" },
  { code: "+229", label: "Benin", iso: "bj" },
  { code: "+1", label: "Bermuda", iso: "bm" },
  { code: "+975", label: "Bhutan", iso: "bt" },
  { code: "+591", label: "Bolivia", iso: "bo" },
  { code: "+387", label: "Bosnia and Herzegovina", iso: "ba" },
  { code: "+267", label: "Botswana", iso: "bw" },
  { code: "+55", label: "Brazil", iso: "br" },
  { code: "+673", label: "Brunei", iso: "bn" },
  { code: "+359", label: "Bulgaria", iso: "bg" },
  { code: "+226", label: "Burkina Faso", iso: "bf" },
  { code: "+257", label: "Burundi", iso: "bi" },
  { code: "+855", label: "Cambodia", iso: "kh" },
  { code: "+237", label: "Cameroon", iso: "cm" },
  { code: "+1", label: "Canada", iso: "ca" },
  { code: "+238", label: "Cape Verde", iso: "cv" },
  { code: "+1", label: "Cayman Islands", iso: "ky" },
  { code: "+236", label: "Central African Republic", iso: "cf" },
  { code: "+235", label: "Chad", iso: "td" },
  { code: "+56", label: "Chile", iso: "cl" },
  { code: "+86", label: "China", iso: "cn" },
  { code: "+57", label: "Colombia", iso: "co" },
  { code: "+269", label: "Comoros", iso: "km" },
  { code: "+242", label: "Congo", iso: "cg" },
  { code: "+243", label: "Congo, Democratic Republic", iso: "cd" },
  { code: "+682", label: "Cook Islands", iso: "ck" },
  { code: "+506", label: "Costa Rica", iso: "cr" },
  { code: "+385", label: "Croatia", iso: "hr" },
  { code: "+53", label: "Cuba", iso: "cu" },
  { code: "+357", label: "Cyprus", iso: "cy" },
  { code: "+420", label: "Czech Republic", iso: "cz" },
  { code: "+45", label: "Denmark", iso: "dk" },
  { code: "+253", label: "Djibouti", iso: "dj" },
  { code: "+1", label: "Dominica", iso: "dm" },
  { code: "+1", label: "Dominican Republic", iso: "do" },
  { code: "+593", label: "Ecuador", iso: "ec" },
  { code: "+20", label: "Egypt", iso: "eg" },
  { code: "+503", label: "El Salvador", iso: "sv" },
  { code: "+240", label: "Equatorial Guinea", iso: "gq" },
  { code: "+291", label: "Eritrea", iso: "er" },
  { code: "+372", label: "Estonia", iso: "ee" },
  { code: "+251", label: "Ethiopia", iso: "et" },
  { code: "+500", label: "Falkland Islands", iso: "fk" },
  { code: "+298", label: "Faroe Islands", iso: "fo" },
  { code: "+679", label: "Fiji", iso: "fj" },
  { code: "+358", label: "Finland", iso: "fi" },
  { code: "+33", label: "France", iso: "fr" },
  { code: "+241", label: "Gabon", iso: "ga" },
  { code: "+220", label: "Gambia", iso: "gm" },
  { code: "+995", label: "Georgia", iso: "ge" },
  { code: "+49", label: "Germany", iso: "de" },
  { code: "+233", label: "Ghana", iso: "gh" },
  { code: "+350", label: "Gibraltar", iso: "gi" },
  { code: "+30", label: "Greece", iso: "gr" },
  { code: "+299", label: "Greenland", iso: "gl" },
  { code: "+1", label: "Grenada", iso: "gd" },
  { code: "+1", label: "Guam", iso: "gu" },
  { code: "+502", label: "Guatemala", iso: "gt" },
  { code: "+224", label: "Guinea", iso: "gn" },
  { code: "+245", label: "Guinea-Bissau", iso: "gw" },
  { code: "+592", label: "Guyana", iso: "gy" },
  { code: "+509", label: "Haiti", iso: "ht" },
  { code: "+504", label: "Honduras", iso: "hn" },
  { code: "+852", label: "Hong Kong", iso: "hk" },
  { code: "+36", label: "Hungary", iso: "hu" },
  { code: "+354", label: "Iceland", iso: "is" },
  { code: "+91", label: "India", iso: "in" },
  { code: "+62", label: "Indonesia", iso: "id" },
  { code: "+98", label: "Iran", iso: "ir" },
  { code: "+964", label: "Iraq", iso: "iq" },
  { code: "+353", label: "Ireland", iso: "ie" },
  { code: "+972", label: "Israel", iso: "il" },
  { code: "+39", label: "Italy", iso: "it" },
  { code: "+225", label: "Ivory Coast", iso: "ci" },
  { code: "+1", label: "Jamaica", iso: "jm" },
  { code: "+81", label: "Japan", iso: "jp" },
  { code: "+962", label: "Jordan", iso: "jo" },
  { code: "+7", label: "Kazakhstan", iso: "kz" },
  { code: "+254", label: "Kenya", iso: "ke" },
  { code: "+686", label: "Kiribati", iso: "ki" },
  { code: "+383", label: "Kosovo", iso: "xk" },
  { code: "+965", label: "Kuwait", iso: "kw" },
  { code: "+996", label: "Kyrgyzstan", iso: "kg" },
  { code: "+856", label: "Laos", iso: "la" },
  { code: "+371", label: "Latvia", iso: "lv" },
  { code: "+961", label: "Lebanon", iso: "lb" },
  { code: "+266", label: "Lesotho", iso: "ls" },
  { code: "+231", label: "Liberia", iso: "lr" },
  { code: "+218", label: "Libya", iso: "ly" },
  { code: "+423", label: "Liechtenstein", iso: "li" },
  { code: "+370", label: "Lithuania", iso: "lt" },
  { code: "+352", label: "Luxembourg", iso: "lu" },
  { code: "+853", label: "Macao", iso: "mo" },
  { code: "+389", label: "Macedonia", iso: "mk" },
  { code: "+261", label: "Madagascar", iso: "mg" },
  { code: "+265", label: "Malawi", iso: "mw" },
  { code: "+60", label: "Malaysia", iso: "my" },
  { code: "+960", label: "Maldives", iso: "mv" },
  { code: "+223", label: "Mali", iso: "ml" },
  { code: "+356", label: "Malta", iso: "mt" },
  { code: "+692", label: "Marshall Islands", iso: "mh" },
  { code: "+222", label: "Mauritania", iso: "mr" },
  { code: "+230", label: "Mauritius", iso: "mu" },
  { code: "+262", label: "Mayotte", iso: "yt" },
  { code: "+52", label: "Mexico", iso: "mx" },
  { code: "+691", label: "Micronesia", iso: "fm" },
  { code: "+373", label: "Moldova", iso: "md" },
  { code: "+377", label: "Monaco", iso: "mc" },
  { code: "+976", label: "Mongolia", iso: "mn" },
  { code: "+382", label: "Montenegro", iso: "me" },
  { code: "+1", label: "Montserrat", iso: "ms" },
  { code: "+212", label: "Morocco", iso: "ma" },
  { code: "+258", label: "Mozambique", iso: "mz" },
  { code: "+95", label: "Myanmar", iso: "mm" },
  { code: "+264", label: "Namibia", iso: "na" },
  { code: "+674", label: "Nauru", iso: "nr" },
  { code: "+977", label: "Nepal", iso: "np" },
  { code: "+31", label: "Netherlands", iso: "nl" },
  { code: "+687", label: "New Caledonia", iso: "nc" },
  { code: "+64", label: "New Zealand", iso: "nz" },
  { code: "+505", label: "Nicaragua", iso: "ni" },
  { code: "+227", label: "Niger", iso: "ne" },
  { code: "+234", label: "Nigeria", iso: "ng" },
  { code: "+683", label: "Niue", iso: "nu" },
  { code: "+672", label: "Norfolk Island", iso: "nf" },
  { code: "+47", label: "Norway", iso: "no" },
  { code: "+968", label: "Oman", iso: "om" },
  { code: "+92", label: "Pakistan", iso: "pk" },
  { code: "+680", label: "Palau", iso: "pw" },
  { code: "+970", label: "Palestine", iso: "ps" },
  { code: "+507", label: "Panama", iso: "pa" },
  { code: "+675", label: "Papua New Guinea", iso: "pg" },
  { code: "+595", label: "Paraguay", iso: "py" },
  { code: "+51", label: "Peru", iso: "pe" },
  { code: "+63", label: "Philippines", iso: "ph" },
  { code: "+48", label: "Poland", iso: "pl" },
  { code: "+351", label: "Portugal", iso: "pt" },
  { code: "+1", label: "Puerto Rico", iso: "pr" },
  { code: "+974", label: "Qatar", iso: "qa" },
  { code: "+40", label: "Romania", iso: "ro" },
  { code: "+7", label: "Russia", iso: "ru" },
  { code: "+250", label: "Rwanda", iso: "rw" },
  { code: "+685", label: "Samoa", iso: "ws" },
  { code: "+378", label: "San Marino", iso: "sm" },
  { code: "+239", label: "Sao Tome and Principe", iso: "st" },
  { code: "+966", label: "Saudi Arabia", iso: "sa" },
  { code: "+221", label: "Senegal", iso: "sn" },
  { code: "+381", label: "Serbia", iso: "rs" },
  { code: "+248", label: "Seychelles", iso: "sc" },
  { code: "+232", label: "Sierra Leone", iso: "sl" },
  { code: "+65", label: "Singapore", iso: "sg" },
  { code: "+421", label: "Slovakia", iso: "sk" },
  { code: "+386", label: "Slovenia", iso: "si" },
  { code: "+677", label: "Solomon Islands", iso: "sb" },
  { code: "+252", label: "Somalia", iso: "so" },
  { code: "+27", label: "South Africa", iso: "za" },
  { code: "+82", label: "South Korea", iso: "kr" },
  { code: "+34", label: "Spain", iso: "es" },
  { code: "+94", label: "Sri Lanka", iso: "lk" },
  { code: "+249", label: "Sudan", iso: "sd" },
  { code: "+597", label: "Suriname", iso: "sr" },
  { code: "+268", label: "Swaziland", iso: "sz" },
  { code: "+46", label: "Sweden", iso: "se" },
  { code: "+41", label: "Switzerland", iso: "ch" },
  { code: "+963", label: "Syria", iso: "sy" },
  { code: "+886", label: "Taiwan", iso: "tw" },
  { code: "+992", label: "Tajikistan", iso: "tj" },
  { code: "+255", label: "Tanzania", iso: "tz" },
  { code: "+66", label: "Thailand", iso: "th" },
  { code: "+228", label: "Togo", iso: "tg" },
  { code: "+676", label: "Tonga", iso: "to" },
  { code: "+1", label: "Trinidad and Tobago", iso: "tt" },
  { code: "+216", label: "Tunisia", iso: "tn" },
  { code: "+90", label: "Turkey", iso: "tr" },
  { code: "+993", label: "Turkmenistan", iso: "tm" },
  { code: "+1", label: "Turks and Caicos Islands", iso: "tc" },
  { code: "+688", label: "Tuvalu", iso: "tv" },
  { code: "+1", label: "U.S. Virgin Islands", iso: "vi" },
  { code: "+380", label: "Ukraine", iso: "ua" },
  { code: "+971", label: "United Arab Emirates", iso: "ae" },
  { code: "+44", label: "United Kingdom", iso: "gb" },
  { code: "+1", label: "United States", iso: "us" },
  { code: "+598", label: "Uruguay", iso: "uy" },
  { code: "+998", label: "Uzbekistan", iso: "uz" },
  { code: "+678", label: "Vanuatu", iso: "vu" },
  { code: "+58", label: "Venezuela", iso: "ve" },
  { code: "+84", label: "Vietnam", iso: "vn" },
  { code: "+681", label: "Wallis and Futuna", iso: "wf" },
  { code: "+967", label: "Yemen", iso: "ye" },
  { code: "+260", label: "Zambia", iso: "zm" },
  { code: "+263", label: "Zimbabwe", iso: "zw" },
];
export default countries;
